import { Github, Mail, User, Linkedin, Twitter } from 'lucide-react';
import React from 'react';



const dataProviders =[
    {
      id: 1,
      name: "GitHub UserName",
      description: "Prove your GitHub User Name",
      icon: <Github size={24} />,
      logo: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",
      users: 386,
      active: true,
      verified: true,
      providerId: "6d3f6753-7ee6-49ee-a545-62f1b1822ae5",
    },
    {
      id: 2,
      name: "Gmail Account",
      description: "Proves your gmail Id",
      icon: <Mail size={24} />,
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Gmail_icon_%282020%29.svg/2560px-Gmail_icon_%282020%29.svg.png",
      users: 192,
      active: true,
      verified: true,
      providerId: "f9f383fd-32d9-4c54-942f-5e9fda349762",
    },
    {
      id: 3,
      name: "Binance KYC Level",
      description: "Name, Surname, DOB, Status",
      icon: <User size={24} />,
      logo: "https://public.bnbstatic.com/20190405/eb2349c3-b2f8-4a93-a286-8f86a62ea9d8.png",
      users: 85,
      active: true,
      verified: true,
      providerId: "2b22db5c-78d9-4d82-84f0-a9e0a4ed0470",
    },
    {
      id: 4,
      name: "LinkedIn - User Profile",
      description: "Verify user profile details from linkedin",
      icon: <Linkedin size={24} />,
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/800px-LinkedIn_logo_initials.png",
      users: 84,
      active: true,
      verified: true,
      providerId: "a9f1063c-06b7-476a-8410-9ff6e427e637",
    },
    {
      id: 5,
      name: "Twitter Follow Check",
      description: "Twitter Follow Check",
      icon: <Twitter size={24} />,
      logo: "https://about.twitter.com/content/dam/about-twitter/x/brand-toolkit/logo-black.png.twimg.1920.png",
      users: 51,
      active: true,
      verified: true,
      providerId: "71901e6a-0548-414f-affb-c60d66e9648g",
    },
    {
      id: 6,
      name: "identity_github00",
      description: "Prove your GitHub User Name",
      icon: <Github size={24} />,
      logo: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",
      users: 42,
      active: true,
      verified: true,
    },
    {
      id: 7,
      name: "Twitter User Profile",
      description: "Verifies twitter profile of user",
      icon: <Twitter size={24} />,
      logo: "https://about.twitter.com/content/dam/about-twitter/x/brand-toolkit/logo-black.png.twimg.1920.png",
      users: 39,
      active: true,
      verified: true,
    },
    {
      id: 8,
      name: "LinkedIn - User Profile Details",
      description: "Verify user profile details from linkedin",
      icon: <Linkedin size={24} />,
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/800px-LinkedIn_logo_initials.png",
      users: 32,
      active: true,
      verified: true,
    },
  ]

  export default dataProviders;